id = "messaging01"

bind = "0.0.0.0:8447"
grpc_bind = "0.0.0.0:7447"

nexus_addr = "localhost:7001"

[debug]
database = false
print_routes = false

[calling]
api_key = "APIZwKRLAWaWa8d"
api_secret = "wdu3fnKDwlsIW17tLhlRKpx275kPJGwRKMC7JADNaXU"
endpoint = "hydrogen-kcvgdwpe.livekit.cloud"
token_duration = 43200
empty_timeout_duration = 600
max_participants = 20

[security]
internal_public_key = "keys/internal_public_key.pem"
reply_token_secret = "QSu8iYYLDkGj10H3FtNI7OabpGl8N7Rg6rBagofQN4Uza3nIrXpVzDEfAiU1G2Yn"
